micronaut:
  application:
    name: moex2
  server:
    port: ${APP_PORT}
datasources:
  liquibase:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    db-type: postgresql
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      dialect: postgres
      options:
        currentSchema: public
        driver: pool
        protocol:
          postgres
liquibase:
  enabled: true
  datasources:
    liquibase:
      enabled: true
      change-log: 'classpath:db/changelog-master.xml'

micronaut.http.services.moex.url: https://iss.moex.com
micronaut.http.client.ssl.insecure-trust-all-certificates: true

logger:
  levels:
    root: INFO
    io.micronaut.http.client: DEBUG
    ru.exdata.moex: DEBUG
